language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9
      env: TOXENV=py39
install:
  - pip install poetry
  - pip install tox
script:
  - tox -e $TOXENV